export default {
  // TODO: Make these dates the actual dates of the hackathon
  hackathon_year: 2024,
  hackathon_date_range: "February 16-18",
  locations: [
    "Outside USA",
    "Alabama",
    "Alaska",
    "American Samoa",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District Of Columbia",
    "Florida",
    "Georgia",
    "Guam",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
    "US Territories",
  ],
  deadlines: [
    {
      key: "oos",
      label: "out-of-state",
      date: "2023-12-12T07:59:00.000Z",
        display_date: "December 11th, 2023",
    },
    {
      key: "is",
      label: "in-state",
      date: "2023-12-12T07:59:00.000Z",
      display_date: "December 11th, 2023",
    },
    {
      key: "stanford",
      label: "Stanford student",
      date: "2024-01-13T07:59:00.000Z",
      display_date: "January 12th, 2024",
    },
  ],
  logo: require("./assets/logo.svg"),
  favicon: require("./assets/favicon.ico"),
  dashboard_background: require("./assets/combined_circuit.svg"),
};
