export var USER_ID_UPDATE = "test_user_id_update";
export var USER_ID = "test_user_id";
export var STATUS = {
    INCOMPLETE: "incomplete",
    SUBMITTED: "submitted",
    WAITLISTED: "waitlisted",
    REJECTED: "rejected",
    ADMITTED: "admitted",
    ADMISSION_CONFIRMED: "admission_confirmed",
    ADMISSION_DECLINED: "admission_declined"
}
export var TRANSPORTATION_STATUS = {
  PENDING: "pending",
  UNAVAILABLE: "unavailable",
  AVAILABLE: "available",
  SUBMITTED: "submitted",
  REJECTED: "rejected",
  APPROVED: "approved",
  PAID: "paid"
}

export var ALLOWED_TRANSITIONS_USER = {
  [STATUS.ADMITTED]: [STATUS.ADMISSION_CONFIRMED, STATUS.ADMISSION_DECLINED],
  [STATUS.ADMISSION_CONFIRMED]: [STATUS.ADMISSION_DECLINED],
  [STATUS.ADMISSION_DECLINED]: [STATUS.ADMISSION_CONFIRMED],
  [TRANSPORTATION_STATUS.AVAILABLE]: [TRANSPORTATION_STATUS.SUBMITTED],
  [TRANSPORTATION_STATUS.REJECTED]: [TRANSPORTATION_STATUS.AVAILABLE]
}

export var ALLOWED_TRANSITIONS_ADMIN = {
  // [STATUS.INCOMPLETE]: [STATUS.SUBMITTED],
  // [STATUS.SUBMITTED]: [STATUS.ADMITTED, STATUS.WAITLISTED, STATUS.REJECTED],
  // [STATUS.WAITLISTED]: [STATUS.ADMITTED],
  // [STATUS.ADMITTED]: [STATUS.ADMISSION_CONFIRMED, STATUS.ADMISSION_DECLINED],
  // [STATUS.REJECTED]: [],
  // [STATUS.ADMISSION_CONFIRMED]: [STATUS.ADMISSION_DECLINED],
  // [STATUS.ADMISSION_DECLINED]: [STATUS.ADMISSION_CONFIRMED],
  [TRANSPORTATION_STATUS.PENDING]: [TRANSPORTATION_STATUS.AVAILABLE, TRANSPORTATION_STATUS.UNAVAILABLE],
  [TRANSPORTATION_STATUS.SUBMITTED]: [TRANSPORTATION_STATUS.APPROVED, TRANSPORTATION_STATUS.REJECTED],
  [TRANSPORTATION_STATUS.REJECTED]: [TRANSPORTATION_STATUS.PAID]
}

export var TRANSPORTATION_TYPE = {
  BUS: "bus",
  FLIGHT: "flight",
  OTHER: "other"
}