export var USER_ID_UPDATE = "test_user_id_update";
export var USER_ID = "test_user_id";
export var STATUS = {
    INCOMPLETE: "incomplete",
    SUBMITTED: "submitted",
    WAITLISTED: "waitlisted",
    REJECTED: "rejected",
    ADMITTED: "admitted",
    ADMISSION_CONFIRMED: "admission_confirmed",
    ADMISSION_DECLINED: "admission_declined"
}

// todo: need to use these below.

export var ALLOWED_TRANSITIONS_ADMIN = {
  [STATUS.INCOMPLETE]: [STATUS.SUBMITTED],
  [STATUS.SUBMITTED]: [STATUS.ADMITTED, STATUS.WAITLISTED, STATUS.REJECTED],
  [STATUS.WAITLISTED]: [STATUS.ADMITTED],
  [STATUS.ADMITTED]: [STATUS.ADMISSION_CONFIRMED, STATUS.ADMISSION_DECLINED],
  [STATUS.REJECTED]: [],
  [STATUS.ADMISSION_CONFIRMED]: [STATUS.ADMISSION_DECLINED],
  [STATUS.ADMISSION_DECLINED]: [STATUS.ADMISSION_CONFIRMED],
}

export var ALLOWED_TRANSITIONS_USER = {
  [STATUS.ADMITTED]: [STATUS.ADMISSION_CONFIRMED, STATUS.ADMISSION_DECLINED],
  [STATUS.ADMISSION_CONFIRMED]: [STATUS.ADMISSION_DECLINED],
  [STATUS.ADMISSION_DECLINED]: [STATUS.ADMISSION_CONFIRMED],
}